WIP: Login
FoodIsLifeBGP/banana-admin pull request #32
Opened 2022-09-10 21:44 UTC by tackc

[//]: # (WIP: Login Page: "[TR_23] LoginPage UI")

---

#### Please check if the PR fulfills these requirements

- [x] The changes don't come from your master branch. ([Source](https://blog.jasonmeridth.com/posts/do-not-issue-pull-requests-from-your-master-branch/)) 

---

### [Card #23](https://trello.com/c/q3QEbZMj)

#### What kind of change does this PR introduce? (bug fix, feature, docs update, ...)
- Add .env to .gitignore (remove associated files from GitHub)
- Add .eslintrc.js to .gitignore (remove associated files from GitHub)
- Add yarn.lock to .gitignore
- Update Storybook builder config to use webpack5
- Add to `Environment Variables` section to README
- Update dependencies and devDependencies
- Add app.config.js
- Update scripts for `bootstrap` and `popper.js` in `index.html`
- Update routes in `App.js`
  - Update `/` to load `LoginPage` component
  - Add `/home` to load `HomePage` component
- Update `Input` component and associated styles
- Build `LoginPage` Page component & associated stylesheet
- Create `tsconfig.json` file
- Begin building associated login files (NOT COMPLETE)

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

#### What is the current behavior? (You can also link to an open issue here)
There were several deprecated packages in use that were causing app issues

#### What is the new behavior? (if this is a feature change)
App should start without errors

#### Does this PR introduce a breaking change? (What changes might users need to make in their application due to this PR?)
I'm not aware of any breaking changes

#### Images (before/ after screenshots, interaction GIFs, ...)

#### Please test your work using the [Accessibility Insights for Web](https://chrome.google.com/webstore/detail/accessibility-insights-fo/pbjjkligggfmakdaogkfomddhfmpjeni) plugin. Include any relevant notes and screenshots.

---

#### TODO
- Login functionality has begun, but is not complete

2022-09-11 18:58 UTC, renburnett requested changes
just had a few issues, but overall looks great! ✔️

2022-09-11 18:58 UTC, renburnett commented on README.md
> +REACT_APP_BASE_URL=http://localhost:3000
is this accurate? it looks like the `API_BASE_URL` gets set in `environment.ts`

2022-09-11 18:58 UTC, renburnett commented on src/Pages/LoginPage/index.js
> +		<div className={styles.container}>
(obv not necessary) but if you're using vscode and want to change your indentation settings:

`Code > Preferences > Settings`
Editor: Tab Size: 2

2022-09-11 18:58 UTC, renburnett commented on src/state/actions/auth.ts
> +    const response = await railsAxios().post(
this is probably the better way to format a request. I might even update the `API.js` file to be axios and async/await based like it is here.

2022-09-11 18:58 UTC, renburnett commented on src/state/actions/passwordReset.ts
> +	const { userIdentity } = store.state;
tabbing/spacing

2022-09-11 19:05 UTC, renburnett requested changes
Per this commit: https://github.com/FoodIsLifeBGP/banana-admin/pull/32/commits/237569cdb1aba7464674fb245ed37c21eb2cf74f

I know theyre not fun to play with.... (i certainly have run into my fair share of problems) 😂 but linters _are_ helpful for consistency/readability across a codebase... I think if we remove this linter we should have a bit of a group vote/consensus. was there a rule that you had run into that we could turn into a warning instead of an error?

2022-09-11 19:17 UTC, tackc commented on .gitignore
> +yarn.lock
I removed yarn.lock from .gitignore

2022-10-08 18:54 UTC, tackc commented
Hey @renburnett,

Will you please take a glance at the updated PR and merge if everything seems to be in-order (hopefully I resolved all issues)

2022-10-15 21:51 UTC, renburnett approved these changes
we chatted, looks good!

2022-10-15 21:52 UTC, merged