Feature/reusable datatable
FoodIsLifeBGP/banana-admin pull request #59
Opened 2023-10-24 08:21 UTC by sherviniv

## Pull Request Template

#### Please check if the PR fulfills these requirements

- [ ] The changes don't come from your master branch. ([Source](https://blog.jasonmeridth.com/posts/do-not-issue-pull-requests-from-your-master-branch/)) 

---

### [Trello Card](trello.com/LINK-TO-TRELLO-CARD)

#### What kind of change does this PR introduce? (bug fix, feature, docs update, ...)

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

#### What is the current behavior? (You can also link to an open issue here)

#### What is the new behavior? (if this is a feature change)
A table with call-back functions, pagination, sorting, searching, and dynamic cell rendering.

#### Does this PR introduce a breaking change? (What changes might users need to make in their application due to this PR?)

#### Other information
.eslintrc.js:
` 'linebreak-style': ['error', process.platform === 'win32' ? 'windows' : 'unix'],`
The configuration sets the expected line endings to be 'windows' if the operating system is Windows, and 'unix' if the operating system is not Windows
`'react/no-unstable-nested-components': 'off',`
For dynamic component rendering inside another one.

**ClientsPage has been implemented in order to show Table usage**

#### Discussion Questions

#### Images (before/ after screenshots, interaction GIFs, ...)

#### Please test your work using the [Accessibility Insights for Web](https://chrome.google.com/webstore/detail/accessibility-insights-fo/pbjjkligggfmakdaogkfomddhfmpjeni) plugin. Include any relevant notes and screenshots.

---

#### TODO:
Use consistent styling for all the project styles

2023-10-28 19:29 UTC, tackc commented on src/Components/DataTable/pagination.jsx
This looks great! Can we implement this reusable DataTable for the DonorsPage also?

2023-10-28 19:30 UTC, tackc commented on src/Components/DataTable/pagination.jsx
Can we also combine this pagination.jsx sub-component with the `Paginator` component already in the repo

2023-11-04 19:29 UTC, renburnett requested changes
looks great just a few small tweaks :)

2023-11-04 19:29 UTC, renburnett commented on src/Pages/ClientsPage/index.js
> +    // let data = mockData.sort((a, b) => {
@sherviniv no big deal, but could you please delete this commented out code, thanks!

2023-11-04 19:29 UTC, renburnett commented on src/Pages/ClientsPage/index.js
> +  const [sortColumn, setSortColumn] = useState({ path: 'no', order: 'asc' });
@sherviniv no biggie but could you please change this to reflect what the variable names will be once this is merged

should be  `order` and `sort_by`

see open sort PR here:
https://github.com/FoodIsLifeBGP/banana-rails/pull/168/files#r1375314653

2023-11-04 19:29 UTC, renburnett commented on src/Pages/AllDonorsPage/index.js
> +    // let data = mockData.sort((a, b) => {
please remove

2023-11-04 19:29 UTC, renburnett commented on src/Pages/DonorPage/index.js
> +    // let data = mockData.sort((a, b) => {
please remove

2023-11-04 19:29 UTC, renburnett commented on src/Pages/DonorPage/index.js
> +  const [sortColumn, setSortColumn] = useState({ path: 'no', order: 'asc' });
@sherviniv could you please change this to reflect what the variable names will be 
should be  `order` and `sort_by`

see open sort PR here:
https://github.com/FoodIsLifeBGP/banana-rails/pull/168/files#r1375314653

2023-11-04 19:38 UTC, renburnett approved these changes
looks great ! 🚀

2023-11-04 19:38 UTC, merged